### ISSUE TITLE
trian/test.prototxt

### ISSUE THREAD

**Issue by foralliance** [Robert-JunWang/Pelee#13]
@Robert-JunWang 

I found that in the final prediction, **`stage4_tb/ext/pm2/res`** was used to make two predictions, except that the `min_size` and `max_size` settings in the "PriorBox" were different, all the others are same

Why do you make two predictions separately instead of merging them? What are the advantages of these two predictions?

**Comment by Robert-JunWang** [comment]
You can merge them, the result should be the same. The reason why I use two predictions separately is to make things easier to try different feature extraction networks. Also, It makes possible to try the unified prediction mentioned in RUN with the last 5 feature maps, but I do not see any improvement on mAP by using unified prediction.

**Comment by foralliance** [comment]
many many thanks
