### ISSUE TITLE
Paper Clarification 

### ISSUE THREAD

**Issue by foralliance** [Robert-JunWang/Pelee#15]
@Robert-JunWang Hi

The paper points:
`Residual prediction block make it possible for us to apply 1x1 convolutional kernels to predict the category scores and box offsets`

Why can use 1*1 here?

The idea of the **Residual Prediction Block** comes from the paper: **Residual features and unified Prediction network for single stage detection**

in the code it provids, it is still 3*3.

**Comment by Robert-JunWang** [comment]
That 1x1 is used to predict location and classes. You can use 1x1 in the original SSD too. But with ResBlock, the accuracy is almost same between 1x1 and 3x3.

**Comment by foralliance** [comment]
many many thanks
