### ISSUE TITLE
Paper Clarification

### ISSUE THREAD

**Issue by foralliance** [Robert-JunWang/Pelee#16]
@Robert-JunWang  Hi

The paper points:
`To compensate for the negative impact on accuracy caused by this change, we use a shallow and wide network structure.  We also add a 1x1 convolution layer after the last dense block to get the stronger representational abilities`

This design, In the code, it doesn't seem to show up.

**Comment by Robert-JunWang** [comment]
They are already in our model. There are only 21 dense layers in total. If you want, you can try use half of the number of dense layers with doubled grow rate for the last two dense blocks. The accuracy is pretty good on Stanford Dogs and the real speed is much faster than the current scheme.
