### ISSUE TITLE
Why I run peleeNet to detect video and cost 78.5ms per image while SSD cost only 40.5ms per image

### ISSUE THREAD

**Issue by zhangjinsong3** [Robert-JunWang/Pelee#18]
First of all, thank you for your work and contribution.
I trained the peleeNet detection network and it behaves pretty good. The model_size of peleeNet is only 20.4M while SSD is 89.1M. However the time of detecting cost 78.5ms per image on my server，by contrast, SSD cost only 40.5ms.
I feel very strange about this phenomenon.

**Comment by ujsyehao** [comment]
You can use `./build/tools/caffe time --model */deploy.prototxt --gpu 0` command to get time cost on each layer.
Running time can be affected by batch size, pre-process(image preprocess), post-process(NMS), code implementation, So we use MACs to evaluate computational cost which can intuitively reflect the running time.

**Comment by zhangjinsong3** [comment]
@ujsyehao  I run it in tensorRT environment, and it run quite faster than SSD,thanks for your contribution again.

**Comment by ujsyehao** [comment]
Can you post your test speed?

**Comment by zhangjinsong3** [comment]
@ujsyehao in tesla P4，with tensorRT soupport ,peleeNet can run in 30ms with the batch_size = 8. While SSD+VGG16 (we have made some compression ) needs 90ms.

**Comment by ujsyehao** [comment]
@zhangjinsong3 Thank you, telsa P4 is P40?

**Comment by zhangjinsong3** [comment]
@ujsyehao Just p4,not p40.

**Comment by ujsyehao** [comment]
@zhangjinsong3 okay, according to graphics card's tflops, the speed is fast.
