### ISSUE TITLE
 ./build/tools/caffe: not found

### ISSUE THREAD

**Issue by MrWhiteHomeman** [Robert-JunWang/Pelee#22]
Hello, thank you for your code!
When I run the train_voc.py, I meet a problem:

args: Namespace(arch='pelee', batch_size=32, image_size=304, kernel_size=1, lr=0.005, posfix='', run_soon=True, step_value=[80000, 100000, 120000], weight_decay=0.0005, weights='models/peleenet_inet_acc7243.caffemodel')
jobs/pelee/VOC0712/SSD_304x304/pelee_SSD_304x304.sh: 2: jobs/pelee/VOC0712/SSD_304x304/pelee_SSD_304x304.sh: ./build/tools/caffe: not found

How can I solve it? Appreciate it you can give me some advice !!!Thank u!!!

**Comment by MrWhiteHomeman** [comment]
I solved！！！

**Comment by aureosun** [comment]
@MrWhiteHomeman 
Sorry,Sir,I met the same problem with you，Could you please share your solutions below?

**Comment by ujsyehao** [comment]
@MrWhiteHomeman you can close the issue.

**Comment by MeaveD** [comment]
@MrWhiteHomeman  would you mind share the solution?
