### ISSUE TITLE
can you provide a test python script?

### ISSUE THREAD

**Issue by MrWhiteHomeman** [Robert-JunWang/Pelee#23]
Thank you for your work!
Can you please provide a python script to detect a single image in test ?

**Comment by ujsyehao** [comment]
@MrWhiteHomeman I will upload demo for detecting single image later.

**Comment by ujsyehao** [comment]
you can refer issue#9

**Comment by Robert-JunWang** [comment]
https://github.com/Robert-JunWang/Pelee/blob/master/detect_eval.ipynb

**Comment by ujsyehao** [comment]
@Robert-JunWang Hi, in your demo code, 
`transformer.set_input_scale('data', 0.017)`
It divides images standard deviation(equal to multiply 1/57.63(0.017)),  57.63 = (58.395 + 57.12 + 57.375) / 3, these standard deviation values are calculated from imagenet dataset.
The operation makes the imagenet dataset images' variance equal to 1, but you train peleenet model on COCO or VOC or COCO + VOC dataset, their standard deviation values should be different from 57.63
