### ISSUE TITLE
Network structure can not be visualized.

### ISSUE THREAD

**Issue by hokuto-HIRANO** [Robert-JunWang/Pelee#27]
python/draw_net.py models/pelee/VOC0712/SSD_304x304/train.prototxt peleeNet.png

The figure of this execution result is plain.
Is the prototxt correct?

**Comment by Robert-JunWang** [comment]
You can use the following link to visualize the network (ignore the warning messages).
http://ethereon.github.io/netscope/#/gist/a797ce07ebfb1e05ed38d106b018f312

**Comment by hokuto-HIRANO** [comment]
Thank you.
