### ISSUE TITLE
I test your model with the ssd/example/ssd/object_detect.cpp,it detect nothing

### ISSUE THREAD

**Issue by zhangyunming** [Robert-JunWang/Pelee#3]
I test your model with the ssd/example/ssd/object_detect.cpp,it detect nothing

i have fix the mean value, what is the problom.

**Comment by zhangyunming** [comment]
it is the ssd_detect.cpp file

**Comment by zhangjinsong3** [comment]
I meet the same problem.

**Comment by Baby47** [comment]
I wonder how you fix the mean value, please tell me.I will be grateful.@zhangyunming

**Comment by zhangjinsong3** [comment]
@Baby47 @zhangyunming peleeNet train with the scale = 0.017. I do it in object_detect.cpp and it works. Thank you very much.

**Comment by ujsyehao** [comment]
@zhangyunming You can close the issue.

**Comment by MennatullahHesham** [comment]
@zhangjinsong3  how do you train with the scale =0.017 ?
i tried 
`
  sample_float *= 0.017; //scal input by 0.017

  cv::Mat sample_normalized;
  cv::subtract(sample_float, mean_, sample_normalized);
`
but it didn;t work 
out : 
I0718 17:31:21.801017 12436 net.cpp:761] Ignoring source layer stem1/bn
.....
I0718 17:31:21.818384 12436 net.cpp:761] Ignoring source layer stage4_tb/ext/pm6/b2c/sc
