### ISSUE TITLE
detection_eval= 0.000040

### ISSUE THREAD

**Issue by MennatullahHesham** [Robert-JunWang/Pelee#34]
Hello
When i try 
Evaluate the model:
cd $CAFFE_ROOT
python examples/pelee/eval_voc.py
![pelee1](https://user-images.githubusercontent.com/40147426/41204232-38a306ee-6ce2-11e8-8893-3bef3b2e7b16.png)
i used pretrained model

**Comment by ujsyehao** [comment]
you can check your *.model and *deploy.prototxt path.

**Comment by MennatullahHesham** [comment]
it should be in  $CAFFE_ROOT/models/
or $CAFFE_ROOT/examples/pelee/models/
i use this command 
> python ./examples/pelee/eval_voc.py --weights=models/peleenet_inet_acc7243.caffemodel

**Comment by ujsyehao** [comment]
peleenet_inet_acc7243.caffemodel is a classification model.
